# location specific configuration to accommodate current source related settings

Location:
    # temp location to save downloaded files
    temp_dir: D:\MounSinai\Darpa\Programming\Sequence_results_downloader\download_temp
