inquiry_file_structure:
    "1": download_source
    "2": url
    "3": destination_name
    "4": destination_dir_path
    "5": unarchive_downloaded

download_source:
    googledrive: GoogleDrive
    nextseq: NextSeq

local_network_sources:
    nextseq: True
    miseq: True
    minerva: True

destination_name:
    box: box
    minerva: Minerva
