inquiry_file_structure:
    "1": download_source
    "2": url
    "3": destination
    "4": destination_directory_path
    "5": unarchive_downloaded

download_source:
    googledrive: GoogleDrive

destination:
    box: box

archive_types:
    zip: zip