  Location:
    # location of a directory with inquiries
    inquiries: D:\MounSinai\Darpa\Programming\DownloadRequestCreator\inquiries
    # path to the folder where application level log files are located (one per application run)
    app_logs: D:\MounSinai\Darpa\Programming\DownloadRequestCreator\logs
    # path to the folder where dynamically created inquiry files for disqualified aliquots will be saved
    inquiries_disqualified_path: reprocess
    # path to the folder where inquiry level log files are located (one log file per inquiry)
    inquiry_logs_relative_path: logs
    # path to the folder where processed inquiry files will be stored
    inquiries_processed_relative_path: processed
    # defines if datetime prefix will be added to the name of the processed files
    processed_add_datestamp: True  # expected values: True, False
