Version: 1.00

Logging:
    #main log - log created by the main application
    #inquiry log - log created for each processed inquiry

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO #INFO
    inquiry_log_level: INFO #INFO

Email:
    #default settings for sending emails
    default_from_email: stas.rirak@mssm.edu
    send_to_emails: ['stasrirak.ms@gmail.com','stas.rirak@mssm.edu','alexandria.vornholt@mssm.edu']
    send_emails: True # expected values: True, False

Validate:
    # if set to True, provided inquiry values will be validated against corresponded entries in the dict_config.yaml
    inquiry_values_vs_dictionary: True # defines if parameters of the inquiry file are being validated vs dictionary
    inquiry_min_number_columns: 4 # required minimum number of column in the inquiry file
    inquiry_validate_number_columns: 4 # expected maximum number of columns to validate in the inquiry file
