Version: 1.00

Logging:
    #main log - log created by the main application
    #inquiry log - log created for each processed inquiry

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO #INFO
    inquiry_log_level: INFO #INFO

Email:
    #default settings for sending emails
    default_from_email: stasrirak.ms@gmail.com
    send_to_emails: ['stasrirak.ms@gmail.com']  # , 'stasrira@yahoo.com'
    send_emails: True # expected values: True, False

#Execute:
#    # if set to true, data downloader file (Location/data_downloader_path) will be executed upon completion
#    # of processing inquiries
#    run_data_downloader: False

Validate:
    # if set to True, provided inquiry values will be validated against corresponded entries in the dict_config.yaml
    inquiry_values_vs_dictionary: True # defines if parameters of the inquiry file are being validated vs dictionary
    inquiry_min_number_columns: 4 # required minimum number of column in the inquiry file
    inquiry_validate_number_columns: 4 # expected maximum number of columns to validate in the inquiry file
